const LocalData = [
  { id2: 1, dusunceler: "basariliyim", puan: 25 },
  { id2: 2, dusunceler: "guzelim", puan: 30 },
  { id2: 3, dusunceler: "caliskanim", puan: 40 },
  { id2: 4, dusunceler: "akilliyim", puan: 50 },
  { id2: 5, dusunceler: "gayretliyim", puan: 30 },
  { id2: 6, dusunceler: "yaparim", puan: 90 },
  { id2: 7, dusunceler: "basariliyim", puan: 20 },
  { id2: 17, dusunceler: "guzelim", puan: 3 },
  { id2: 18, dusunceler: "caliskanim", puan: 4 },
  { id2: 19, dusunceler: "akilliyim", puan: 5 },
  { id2: 20, dusunceler: "gayretliyim", puan: 3 },
  { id2: 22, dusunceler: "yaparim", puan: 9 },
  { id2: 23, dusunceler: "basariliyim", puan: 2 },
  { id2: 25, dusunceler: "guzelim", puan: 3 },
  { id2: 26, dusunceler: "caliskanim", puan: 4 },
  { id2: 27, dusunceler: "akilliyim", puan: 5 },
  { id2: 27, dusunceler: "gayretliyim", puan: 3 },
  { id2: 29, dusunceler: "yaparim", puan: 9 },
  { id2: 30, dusunceler: "basariliyim", puan: 2 },
  { id2: 31, dusunceler: "guzelim", puan: 3 },
  { id2: 32, dusunceler: "caliskanim", puan: 4 },
  { id2: 34, dusunceler: "akilliyim", puan: 5 },
  { id2: 35, dusunceler: "gayretliyim", puan: 3 },
  { id2: 36, dusunceler: "yaparim", puan: 9 },
  { id2: 37, dusunceler: "gayretliyim", puan: 3 },
  { id2: 38, dusunceler: "yaparim", puan: 9 },
  { id2: 44, dusunceler: "basariliyim", puan: 2 },
  { id2: 45, dusunceler: "guzelim", puan: 3 },
  { id2: 46, dusunceler: "caliskanim", puan: 4 },
  { id2: 37, dusunceler: "gayretliyim", puan: 3 },
  { id2: 38, dusunceler: "yaparim", puan: 9 },
  { id2: 44, dusunceler: "basariliyim", puan: 2 },
  { id2: 45, dusunceler: "guzelim", puan: 3 },
  { id2: 46, dusunceler: "caliskanim", puan: 4 },
];

export default LocalData;
